"""Generate Caddyfile for mma-mcp HTTPS with automatic TLS.

Supports two ACME modes:
  - DNS-01 challenge via provider plugin (no port 80 needed)
  - HTTP-01 challenge (requires port 80 open)

API credentials are always read from environment variables, never from config.
"""

from __future__ import annotations

import os
from pathlib import Path

from mma_mcp.config import AppConfig, DNS_PROVIDERS, TlsConfig


def _dns01_global_block(tls: TlsConfig) -> str:
    """Generate the global acme_dns block for DNS-01 challenge."""
    provider = DNS_PROVIDERS[tls.dns_provider]
    env_refs = "\n".join(
        f"        {_provider_field(tls.dns_provider, var)} {{${var}}}"
        for var in provider["env_vars"]
    )
    return f"""\
{{
    acme_dns {tls.dns_provider} {{
{env_refs}
    }}
}}"""


def _provider_field(provider: str, env_var: str) -> str:
    """Map env var name to Caddy plugin field name."""
    # Each plugin has its own field names; derive from env var
    mapping: dict[str, dict[str, str]] = {
        "alidns": {
            "ALIDNS_ACCESS_KEY_ID": "access_key_id",
            "ALIDNS_ACCESS_KEY_SECRET": "access_key_secret",
        },
        "cloudflare": {
            "CLOUDFLARE_API_TOKEN": "api_token",
        },
        "dnspod": {
            "DNSPOD_API_TOKEN": "api_token",
        },
        "godaddy": {
            "GODADDY_API_KEY": "api_key",
            "GODADDY_API_SECRET": "api_secret",
        },
        "namecheap": {
            "NAMECHEAP_API_KEY": "api_key",
            "NAMECHEAP_API_USER": "api_user",
        },
    }
    return mapping.get(provider, {}).get(env_var, env_var.lower())


def generate_caddyfile(config: AppConfig, target: Path | None = None) -> Path:
    """Generate a Caddyfile from the current config and return its path."""
    tls = config.tls
    srv = config.server

    if not tls.domain:
        raise ValueError("tls.domain must be set to generate a Caddyfile")

    parts: list[str] = []

    # Header comment
    parts.append(f"""\
# Caddyfile for mma-mcp
# Generated by: mma-mcp caddyfile
# Domain: {tls.domain}
""")

    # Global block for DNS-01 (if applicable)
    if tls.dns_provider:
        if tls.dns_provider not in DNS_PROVIDERS:
            supported = ", ".join(sorted(DNS_PROVIDERS))
            raise ValueError(
                f"Unknown dns_provider {tls.dns_provider!r}. "
                f"Supported: {supported}"
            )
        provider_info = DNS_PROVIDERS[tls.dns_provider]
        missing = [v for v in provider_info["env_vars"] if not os.environ.get(v)]
        if missing:
            parts.append(f"# WARNING: environment variables not set: {', '.join(missing)}")
            parts.append(f"# Required for {tls.dns_provider}: "
                         f"{', '.join(provider_info['env_vars'])}")
            parts.append(f"# Build Caddy with: xcaddy build --with {provider_info['caddy_plugin']}")
            parts.append("")

        parts.append(_dns01_global_block(tls))
    else:
        parts.append("# Using HTTP-01 ACME challenge (port 80 must be open)")

    parts.append("")

    # Site block
    upstream = f"{srv.host}:{srv.port}"
    parts.append(f"""\
{tls.domain} {{
    reverse_proxy {upstream} {{
        header_up X-Forwarded-Host {{host}}
        header_up Host {{upstream_hostport}}
    }}

    # Optional: Bearer Token auth (uncomment and set your token)
    # @unauthorized not header Authorization "Bearer your-secret-token"
    # respond @unauthorized 401
}}""")

    content = "\n".join(parts) + "\n"
    target = target or Path("Caddyfile")
    target.write_text(content, encoding="utf-8")
    return target
